version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/cms
      - public_data:/cms/public
    env_file:
      - .env
  database:
    image: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  database_data:
  public_data:
