version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/cms
      - paperclip_data:/cms/public/system
      - asset_data:/cms/public/assets
    env_file:
      - .env
  database:
    image: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  database_data:
  paperclip_data:
  asset_data:
