version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - database_data:/var/lib/postgresql/data
volumes:
  database_data:
